- name: Remove compose file if exists before copy new file
  file:
    path: ~/docker-compose.yml
    state: absent

- name: Copy compose file to Ubuntu box
  copy:
    src: docker-compose.yml
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Pull and start wordpress  
  command: docker-compose -f docker-compose.yml up -d
